<a href="https://colab.research.google.com/github/javed163/NLP-/blob/main/day_9_word_embedding_technique_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word embedding techniques using embedding layers in keras

In [3]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [4]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
# vocabulary size is 10000
cov_size = 10000

# one hot representation

In [11]:
one_hot_rep = [one_hot(words, cov_size) for words in sent]
print(one_hot_rep)

[[795, 9363, 9847, 2087], [795, 9363, 9847, 1866], [795, 2174, 9847, 1342], [9502, 8761, 9298, 2648, 7183], [9502, 8761, 9298, 2648, 69], [3769, 795, 687, 9847, 7012], [8666, 2443, 6379, 2648]]


# word embedding representation

In [12]:
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
sent_len = len(sent)
embedding_doc = pad_sequences(one_hot_rep, padding = 'pre', maxlen=sent_len)
print(embedding_doc)

[[   0    0    0  795 9363 9847 2087]
 [   0    0    0  795 9363 9847 1866]
 [   0    0    0  795 2174 9847 1342]
 [   0    0 9502 8761 9298 2648 7183]
 [   0    0 9502 8761 9298 2648   69]
 [   0    0 3769  795  687 9847 7012]
 [   0    0    0 8666 2443 6379 2648]]


In [14]:
dim = 10

In [35]:
model = Sequential()
model.add(Embedding(cov_size,10 , input_length = sent_len))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [36]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.predict(embedding_doc[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step


array([[ 0.00612725,  0.04053125, -0.00880282,  0.03342629,  0.00428345,
        -0.02405235, -0.01360986, -0.00096362, -0.04849559, -0.01172241],
       [ 0.00612725,  0.04053125, -0.00880282,  0.03342629,  0.00428345,
        -0.02405235, -0.01360986, -0.00096362, -0.04849559, -0.01172241],
       [ 0.00612725,  0.04053125, -0.00880282,  0.03342629,  0.00428345,
        -0.02405235, -0.01360986, -0.00096362, -0.04849559, -0.01172241],
       [ 0.02319987,  0.03848919, -0.00095988,  0.01188559,  0.01360034,
         0.03504649,  0.01862014,  0.02092406, -0.02666966,  0.04320866],
       [-0.01670905, -0.02919173, -0.04337807, -0.02526492, -0.00139564,
         0.02046755,  0.00751489, -0.01134988, -0.02385812, -0.00816907],
       [ 0.00932432, -0.04035089,  0.0440835 , -0.02352437, -0.01741284,
        -0.02346807,  0.01974112, -0.02364978, -0.04916095, -0.01937634],
       [ 0.02162287, -0.04551345, -0.01270319,  0.04742631, -0.03881751,
        -0.01650437, -0.00908   , -0.00422195

In [27]:
print(model.predict(embedding_doc))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 902ms/step
[[[-2.58246791e-02 -2.06206925e-02 -1.75144896e-02  1.17503628e-02
    4.89812978e-02 -2.20578443e-02 -2.90968549e-02  2.10108422e-02
   -2.48093251e-02  2.54102089e-02]
  [-2.58246791e-02 -2.06206925e-02 -1.75144896e-02  1.17503628e-02
    4.89812978e-02 -2.20578443e-02 -2.90968549e-02  2.10108422e-02
   -2.48093251e-02  2.54102089e-02]
  [-2.58246791e-02 -2.06206925e-02 -1.75144896e-02  1.17503628e-02
    4.89812978e-02 -2.20578443e-02 -2.90968549e-02  2.10108422e-02
   -2.48093251e-02  2.54102089e-02]
  [-1.27554052e-02 -4.32868116e-02 -3.19566578e-03  3.59214842e-04
   -2.95317061e-02  7.57293776e-03 -3.45284119e-02  4.51141261e-02
    6.53902441e-03  4.30138968e-02]
  [-2.57098321e-02 -4.92228530e-02  8.47153738e-03 -8.66387039e-03
    4.20007817e-02  2.75126360e-02  9.79017466e-04 -6.64383173e-03
   -2.40058899e-02 -2.42474563e-02]
  [ 4.18342240e-02  4.53033783e-02 -2.68747807e-02 -4.44101691e-02
   -2.54310723e-02  5.45376539e-03 -1.464436

In [38]:
# assignment
sent = ['the word is amazing',
        'you are the peson who have something good',
        'the world is become the most beautiful',
        'i will become the datascient with 3 months',
        'i am learnig datascience']

In [39]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot

In [40]:
voc_size = 1000


In [62]:
max_lenght = len(sent)

In [63]:
doc = [one_hot(words, voc_size) for words in sent]
print(doc)

[[354, 174, 963, 854], [988, 196, 354, 719, 650, 743, 266, 677], [354, 247, 963, 118, 354, 342, 305], [754, 5, 118, 354, 144, 475, 802, 341], [754, 301, 681, 28]]


In [64]:
embd_doc = pad_sequences(doc, padding = 'post', maxlen = max_lenght)
print(embd_doc)

[[354 174 963 854   0]
 [719 650 743 266 677]
 [963 118 354 342 305]
 [354 144 475 802 341]
 [754 301 681  28   0]]


In [66]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = max_lenght))


In [67]:
model.compile('adam','mse')

In [68]:
model.summary()

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)             │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [69]:
model.predict(embd_doc[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step


array([[-0.02518213, -0.03494783,  0.00950012, -0.04399418, -0.03819739,
        -0.0489779 ,  0.01477008, -0.04784925,  0.00047857, -0.02136837],
       [-0.00896683,  0.01815956,  0.02707114,  0.0355466 , -0.0260837 ,
        -0.04928894,  0.01215929,  0.01446649, -0.03832281, -0.01728987],
       [ 0.0494729 ,  0.01177809, -0.00566556,  0.00762799, -0.04899685,
         0.0009599 , -0.03936251, -0.04194064, -0.01972291,  0.025329  ],
       [-0.04290548,  0.01111708, -0.02718065, -0.01730411, -0.02087911,
         0.04434789,  0.03841018, -0.02345273,  0.00910919,  0.03569644],
       [ 0.01422532, -0.00112299,  0.01185125, -0.04039764, -0.02861805,
         0.0255281 , -0.0084119 , -0.00696361, -0.0291772 ,  0.00028921]],
      dtype=float32)